#!/usr/bin/env bash
mkdir ~/nixos_backup
sudo cp /etc/nixos/* ~/nixos_backup/
sudo rm -r /etc/nixos
sudo stow -t /etc/nixos/ nixos
cp ./wallpaper/.background-image ~/.background-image
ansible-playbook ssh/ssh.yml --ask-vault-pass
