#!/usr/bin/env bash

rm -r ~/.config/home-manager
cp -r home-manager/ ~/.config/home-manager

echo "rebuilding home-manager..."

nix run nixpkgs#home-manager -- switch --flake ~/.config/home-manager/#$USER

echo "restarting sway..."
swaymsg reload

echo "complete"
