#!/usr/bin/env bash

# Define the base directory for dotfiles
BASE_DIR="$HOME/.dotfiles/home-manager"

# Declare an array of directories to stow
declare -a DIRECTORIES=(
    "_nvim"
    "_waybar"
    "_prettier"
    "_scripts"
    "_tmux"
    "_sway"
    "_alacritty"
)

# Change to the base directory
cd "$BASE_DIR" || exit 1

# Loop through each directory and stow it
for DIR in "${DIRECTORIES[@]}"; do
    if [ -d "$DIR" ]; then
        echo "Stowing: $DIR"
        stow -v -R -d "$BASE_DIR" -t "$HOME" "$DIR"
    else
        echo "Skipping: $DIR does not exist."
    fi
done
