{ config, pkgs, ... }:
{
    home.packages = with pkgs; [
        ansible
        automake
        awscli2
        cargo
        cmake
        docker
        eza
        fzf
        gcc
        git
        go
        jq
        neovim
        nodePackages."@angular/cli"
        nodePackages."eslint"
        nodePackages."prettier"
        nodePackages."typescript"
        nodejs
        python312
        ripgrep
        tmux
        unzip
        xclip
        zig
        zip
        zoxide
      ];
}
