{ config, pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    ansible
    btop
    cups
    dbus
    eza
    fzf
    git
    gptfdisk
    jq
    lshw
    neofetch
    ntfs3g
    nvtop
    parted
    pciutils
    ripgrep
    stow
    tmux
    unzip
    usbutils
    wget
    xclip
    zip
    zoxide

    rocmPackages.rocm-runtime
    rocmPackages.rocm-device-libs
    rocmPackages.rocm-core
    rocmPackages.rocm-cmake
    rocmPackages.rocm-smi
    rocmPackages.rocminfo
    rocmPackages.clr
    rocmPackages.hip-common
    rocmPackages.hipcc
    rocmPackages.rocblas
    rocmPackages.hipblas
    rocmPackages.rocsparse
    rocmPackages.roctracer
    rocmPackages.rocprofiler
    amdvlk
  ];
}
