[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x202329"
foreground = "0xabb2bf"

[font]
size = 18.0

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[window]
opacity = 1.0
dynamic_padding = true

[keyboard]
bindings = [
  { key = "B", mods = "Control|Shift", action = "None" },
  { key = "F", mods = "Control|Shift", action = "None" },
  { key = "PageUp", mods = "Shift", action = "ScrollHalfPageUp" },
  { key = "PageDown", mods = "Shift", action = "ScrollHalfPageDown" },
  { key = "Up", mods = "Shift", action = "ScrollLineUp" },
  { key = "Down", mods = "Shift", action = "ScrollLineDown" },
  { key = "Space", mods = "Control", chars = "\u0000" },
]
