- hosts: localhost
  vars:
      user_home: "{{ lookup('env', 'HOME') }}"
      ip: "{{ lookup('env', 'USER') != 'cvhew' }}"
      iw: "{{ lookup('env', 'USER') == 'cvhew' }}"
      source_key: "{{ user_home + '/.dotfiles/ansible/ssh/.ssh/id_ed25519' if ip else user_home + '/.dotfiles/ansible/ssh/.sshc/id_ed25519' }}"
      dest_key: "{{ user_home }}/.ssh/id_ed25519"

  tasks:
    - name: Ensure .ssh directory exists
      file:
          path: "{{ dest_key | dirname }}"
          state: directory
          mode: '0700'

    - name: Install ssh key
      copy:
          src: "{{ source_key }}"
          dest: "{{ dest_key }}"
          mode: '0600'

    - name: Install ssh key public
      copy:
          src: "{{ source_key }}.pub"
          dest: "{{ dest_key }}.pub"
          mode: '0644'

    - name: Set authorized key from file
      authorized_key:
          user: "{{ lookup('env', 'USER') }}"
          state: present
          key: "{{ lookup('file', item) }}"
      loop: "{{ query('fileglob', lookup('env', 'HOME') + '/.ssh/*.pub') }}"
      loop_control:
          label: "{{ item }}"
