- hosts: localhost
  vars:
      user_home: "{{ lookup('env', 'HOME') }}"
      source_config: "./.wakatime.cfg"
      dest_config: "{{ user_home }}/.wakatime.cfg"

  tasks:
      - name: Ensure home directory exists
        file:
            path: "{{ user_home }}"
            state: directory
            mode: "0755"

      - name: Decrypt and move wakatime config
        copy:
            src: "{{ source_config }}"
            dest: "{{ dest_config }}"
            decrypt: yes
            mode: "0600"
