#!/usr/bin/env bash

TRASH_DIR="$HOME/.local/share/trash/store"
LOG_FILE="$HOME/.local/share/trash/trash.log"
mkdir -p "$TRASH_DIR"

trashed_files=()

for file in "$@"; do
    if [[ ! -e "$file" ]]; then
        echo "File '$file' not found!" >&2
        continue
    fi
    timestamp=$(date +%s)
    filename=$(basename -- "$file")
    new_name="${filename}.${timestamp}"
    mv "$file" "$TRASH_DIR/$new_name"
    echo "$timestamp,$new_name,$(realpath "$file")" >>"$LOG_FILE"
    trashed_files+=("$(realpath "$file")")
done

if [[ ${#trashed_files[@]} -gt 0 ]]; then
    echo -e "Moved ${#trashed_files[@]} files to trash:"
    printf '\t%s\n' "${trashed_files[@]}"
fi
