#!/usr/bin/env bash

twofactor="push1"
gateway="DC Gateway"
protocol="gp"
server="vpn.gatech.edu"

# Fetch the password from Bitwarden
bw_secret=$(bw list items --search "Georgia Tech")
username=$(echo "$bw_secret" | jq -r ".[0].login.username")
password=$(echo "$bw_secret" | jq -r ".[0].login.password")
if [ -z "$password" ]; then
  echo "Error: Password not found in Bitwarden."
  exit 1
fi

echo -e "$password\n$twofactor\n$gateway" | sudo openconnect --protocol=$protocol --user=$username --passwd-on-stdin $server
