#!/usr/bin/env bash

# Check if two arguments are given
if [ $# -ne 2 ]; then
    echo "Usage: $0 <old_string> <new_string>"
    exit 1
fi

old_string=$1
new_string=$2

# Loop through files containing the old string and rename them
for file in *"$old_string"*; do
    mv "$file" "${file//$old_string/$new_string}"
done
