# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# ~/.config/starship.toml

format = """
$nix_shell\
$directory\
$git_branch\
$git_status
"""

right_format = """
$cmd_duration\
"""


add_newline = false

[directory]
format = "[ $path ](bold cyan)"
truncation_length = 1
truncation_symbol = ""

[git_branch]
style = "bold red"
format = '[\($branch(:$remote_branch)]($style)'

[git_status]
format = '([$ahead_behind\)]($style) )'

[cmd_duration]
min_time = 0
format = "[$duration](yellow) "
show_milliseconds = true

[nix_shell]
disabled = false
format = '[ \(nix\)](grey) '
