"$schema" = 'https://starship.rs/config-schema.json'

format = """
$nix_shell\
$directory\
$git_branch\
"""

right_format = """
$git_status\
"""

add_newline = false

[directory]
format = " [$path](bold cyan) "
truncation_length = 1
truncation_symbol = ""

[git_branch]
style = "bold red"
format = '[\($branch(:$remote_branch)\)]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold darkgrey"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[nix_shell]
disabled = false
format = '[\(nix\)](grey)'
