"$schema" = 'https://starship.rs/config-schema.json'

format = "$nix_shell$directory$git_branch$git_status"

add_newline = false

[directory]
format = '[ $path](bold cyan) '
truncate_to_repo = true
truncation_length = 1
truncation_symbol = ""

[git_branch]
format = '[\($branch(:$remote_branch)\)](bold red) '

[git_status]
format = '[(\[$ahead_behind\] )]($style)[($all_status)]($style) '
up_to_date = ''
conflicted = ''
untracked = ''
stashed = ''
modified = '✗'
renamed = ''
deleted = ''
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = 'bold yellow'

[nix_shell]
disabled = false
format = '[\(nix\)](grey)'
